---

- name: ClamAV daemon is configured
  lineinfile:
    dest: "{{ clamav_daemon_config_file }}"
    regexp: "^{{ item.key }}\\ "
    line: "{{ item.key }} {{ item.value }}"
  with_dict: "{{ _clamav_config.clamd }}"
  notify:
    - restart clamav freebsd
    - restart clamav linux
    - restart clamav-socket

- name: ClamAV freshclam is configured
  lineinfile:
    dest: "{{ clamav_freshclam_config_file }}"
    regexp: "^{{ item.key }}\\ "
    line: "{{ item.key }} {{ item.value }}"
  with_dict: "{{ _clamav_config.freshclam }}"
  notify:
    - restart freshclam

- name: ClamAV milter is configured
  lineinfile:
    dest: "{{ clamav_milter_config_file }}"
    regexp: "^{{ item.key }}\\ "
    line: "{{ item.key }} {{ item.value }}"
  with_dict: "{{ _clamav_config.milter }}"
  notify:
    - restart clamav-milter
