---
# Debian

- name: Install software
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - clamav
    - clamav-freshclam
    - clamav-milter
    - arj
    - bzip2
    - cabextract
    - cpio
    - file
    - gzip
    - lhasa
    - lzop
    - nomarch
    - p7zip
    - pax
    - rpm
    - unrar-free
    - unzip
    - zip

- name: Enable services
  service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - clamav-freshclam
    - clamav-daemon
    - clamav-milter
