---

# Combine Configuration
- set_fact: _clamav_config="{{ clamav_default_config | combine(clamav_config | default({}), recursive=True) }}"
  no_log: true

- include: prepare.yml
- include: install.yml
- include: configure.yml
- include: update-database.yml
