---

- include_vars: freebsd.yml
  when: ansible_distribution == "FreeBSD"

- include_vars: debian.yml
  when: (ansible_distribution == "Debian") or (ansible_distribution == "Ubuntu")

# Combine Configuration
- set_fact: _clamav_config="{{ clamav_default_config | combine(clamav_config, recursive=True) }}"
  no_log: true

- include: prepare.yml
- include: install.yml
- include: configure.yml
- include: update-database.yml
