---

- name: groups exist
  group:
    name: "{{ item }}"
    state: present
    system: true
  with_items:
    - "{{ _clamav_config.clamd.group }}"
    - "{{ _clamav_config.milter.group }}"

- name: clamav user exists and is part of the milter group
  user:
    name: "{{ _clamav_config.clamd.user }}"
    group: "{{ _clamav_config.clamd.group }}"
    groups: "{{ _clamav_config.milter.group }}"
    append: true
    system: true
  notify:
    - restart clamav-milter

- name: config dir is present
  file:
    path: "{{ _clamav_config.config_dir }}"
    state: directory

