---

- name: config dir is present
  file:
    path: "{{_clamav_config.config_dir}}"
    state: directory

- name: milter is part of the milter group
  user:
    name: "{{_clamav_config.clamd.user}}"
    groups: "{{_clamav_config.milter.group}}"
    append: yes
  notify:
    - restart clamav-milter
