---

- name: milter groups exist
  group:
    name: "{{ clamav_milter_group }}"
    state: present
    system: true

- name: ClamAV user exists and is part of the milter group
  user:
    name: "{{ clamav_user }}"
    groups: "{{ clamav_milter_group }}"
    append: true
    system: true
  notify:
    - restart clamav-milter

- name: ClamAV config directory is present
  file:
    path: "{{ item | dirname }}"
    state: directory
  with_items:
    - "{{ clamav_daemon_config_file }}"
    - "{{ clamav_freshclam_config_file }}"
    - "{{ clamav_milter_config_file }}"

- name: ClamAV daemon socket directory exists
  file:
    path: "{{ clamav_clamd_socket | dirname }}"
    state: directory
    owner: "{{ clamav_user }}"
    group: "{{ clamav_milter_group }}"
    mode: 0770

- name: ClamAV milter direcory exists
  file:
    path: "{{ clamav_milter_socket | dirname }}"
    state: directory
    group: "{{ clamav_milter_group }}"
    mode: "o+rwx,g+rwx"
