---

# ToDo: Detect first run and skip later if auto-updates are enabled

- name: Stop ClamAV before updating the virus database
  service:
    name: clamav-freshclam
    state: stopped
 
- name: Make sure virus database is up to date (this may take long time if the DNS RR picks a bad mirror)
  command: freshclam --config-file {{ clamav_freshclam_config_file }}
  notify:
    - start freshclam
