---

- name: daemon-reload
  command: systemctl daemon-reload

- name: restart clamav-socket
  command: systemctl restart clamav-daemon.socket

- name: start freshclam
  service: name=clamav-freshclam state=started

- name: restart clamav-milter
  service: name=clamav-milter state=restarted

- name: restart freshclam
  service: name=clamav-freshclam state=restarted

# Linux specific

- name: restart clamav linux
  service: name=clamav-daemon state=restarted
  when: ansible_distribution != "FreeBSD"

# FreeBSD specific

- name: restart clamav freebsd
  service: name=clamav-clamd state=restarted
  when: ansible_distribution == "FreeBSD"
